name: Multi-Tenant CI/CD Pipeline

on: workflow_dispatch

permissions:
  contents: read
  packages: write
  
env:
  REGISTRY: docker.io
  IMAGE_NAME: multi-tenant-webapp

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      # ---------------- Checkout ----------------
      - name: Checkout Code
        uses: actions/checkout@v4

      # ---------------- Identify tenant ----------------
      - name: Extract Tenant
        shell: powershell
        run: |
          $BRANCH = $env:GITHUB_REF_NAME
          $TENANT = $BRANCH.Split('/')[0]

          echo "TENANT=$TENANT" >> $env:GITHUB_ENV
          Write-Host "Deploying to namespace: $TENANT"

      # ---------------- Login to Docker ----------------
      - name: Login to Docker Hub
        shell: powershell
        run: |
          #echo "${{ secrets.DOCKER_PASSWORD }}" | podman login docker.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # ---------------- Build Image (Podman) ----------------
      - name: Build Image
        shell: powershell
        run: |
          podman build -t ${env:IMAGE_NAME}:${env:GITHUB_SHA} .

      # ---------------- Tag Image ----------------
      - name: Tag Image
        shell: powershell
        run: |
          podman tag ${env:IMAGE_NAME}:${env:GITHUB_SHA} docker.io/${{ secrets.DOCKER_USERNAME }}/${env:IMAGE_NAME}:${env:GITHUB_SHA}

      # ---------------- Push Image ----------------
      - name: Push Image
        shell: powershell
        run: |
          podman push docker.io/${{ secrets.DOCKER_USERNAME }}/${env:IMAGE_NAME}:${env:GITHUB_SHA}

      # ---------------- Deploy using Helm ----------------
      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install webapp ./charts/webapp --namespace user1 --create-namespace --wait=false -f ./charts/webapp/user1-values.yaml `
            --set image.repository=docker.io/${{ secrets.DOCKER_USERNAME }}/multi-tenant-webapp --set image.tag=$GITHUB_SHA --wait --timeout 120s

      # ---------------- Verify Deployment ----------------
      - name: Check Rollout Status
        run: |
          kubectl rollout status deployment/webapp -n user1 --timeout=120s

      # ---------------- Rollback on Failure ----------------
      - name: Rollback Deployment
        if: failure()
        run: |
          echo "Deployment failed. Rolling back..."
          helm rollback webapp -n user1

      # ---------------- Kafka Event Trigger ----------------
      - name: Send Kafka Deployment Event
        if: success()
        run: |
          python3 - <<EOF
          from kafka import KafkaProducer
          import json, os, datetime

          producer = KafkaProducer(
              bootstrap_servers="kafka.default.svc.cluster.local:9092",
              value_serializer=lambda v: json.dumps(v).encode('utf-8')
          )

          event = {
              "tenant": os.getenv("TENANT"),
              "image": "${{ github.sha }}",
              "status": "DEPLOYED",
              "timestamp": str(datetime.datetime.utcnow())
          }

          producer.send("deployment-events", event)
          producer.flush()

          print("Kafka event sent successfully")
          EOF
